name: snailly
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  app_links: ^3.4.0
  avatar_glow: ^2.0.2
  cupertino_icons: ^1.0.2
  dart_jsonwebtoken: ^2.4.0
  dropdown_search2: 1.0.2
  email_validator: ^2.1.16
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^5.7.2+3
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^9.0.0
  flutter_secure_storage: ^8.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  get: 4.6.5
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  http: ^1.0.0
  intl: ^0.18.0
  lottie: ^2.6.0
  month_picker_dialog: ^2.0.2
  shared_preferences: ^2.0.15
  simple_animations: ^4.0.1
  speech_to_text: ^6.3.0
  supercharged: ^2.1.0
  timeago: ^3.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_white.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter:
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/lottie/
  uses-material-design: true
